Initial commit
Azure/azure-kusto-nlog-sink pull request #1
Opened 2023-04-13 13:05 UTC by asaharn

Added Nlog ADX Custom target

2023-04-13 16:52 UTC, snakefoot commented
Notice to provide an array of parameters (Ex. ColumnMappings), then consider using this (where SinkColumnMapping becomes `class` instead of `struct`)

```c#
[ArrayParameter(typeof(SinkColumnMapping), "columnMapping")]
public IList<SinkColumnMapping> ColumnMappings { get; private set; }
```

Then you can do this in NLog.config:

```xml
<target name="ADXTarget" xsi:type="ADXTarget">
       <columnMapping name="abc" columnType="bing" ValuePath="hello" />
       <columnMapping name="def" columnType="bong" ValuePath="world" />
</target>
```

Or like this in [appsettings.json](https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json):
```json
 "target": {
      "ADXTarget": {
        "type": "ADXTarget",
        "columnMappings": [
          {
            "name": "abc",
            "columnType": "bing",
            "ValuePath": "hello"
          },
          {
            "name": "def",
            "columnType": "bong",
            "ValuePath": "world"
          }
        ]
```

Btw. it looks like this `ColumnMapping` is very hardcoded, and depends on `ADXLogEvent`. So maybe it should not be configurable at all, but just be reflection based on `ADXLogEvent`-properties.

See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target
See also: https://github.com/NLog/NLog/wiki/Properties-constraints-for-custom-extensions

2023-05-09 05:33 UTC, asaharn commented
> Notice to provide an array of parameters (Ex. ColumnMappings), then consider using this (where SinkColumnMapping becomes `class` instead of `struct`)
> 
> ```cs
> [ArrayParameter(typeof(SinkColumnMapping), "columnMapping")]
> public IList<SinkColumnMapping> ColumnMappings { get; private set; }
> ```
> 
> Then you can do this in NLog.config:
> 
> ```
> <target name="ADXTarget" xsi:type="ADXTarget">
>        <columnMapping name="abc" columnType="bing" ValuePath="hello" />
>        <columnMapping name="def" columnType="bong" ValuePath="world" />
> </target>
> ```
> 
> Or like this in [appsettings.json](https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json):
> 
> ```json
>  "target": {
>       "ADXTarget": {
>         "type": "ADXTarget",
>         "columnMappings": [
>           {
>             "name": "abc",
>             "columnType": "bing",
>             "ValuePath": "hello"
>           },
>           {
>             "name": "def",
>             "columnType": "bong",
>             "ValuePath": "world"
>           }
>         ]
> ```
> 
> Btw. it looks like this `ColumnMapping` is very hardcoded, and depends on `ADXLogEvent`. So maybe it should not be configurable at all, but just be reflection based on `ADXLogEvent`-class-properties.
> 
> See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target See also: https://github.com/NLog/NLog/wiki/Properties-constraints-for-custom-extensions

Hi @snakefoot , 
We have decided to remove the columnmappings altogether. Can you see if the asked comments can be negated? 
And really  thankyou for the review,  Can you check now if we are fine now or missing something?

2023-05-10 12:27 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto.sln
> +# Visual Studio Version 17
Got the following warning


C:\Program Files\dotnet\sdk\7.0.203\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3245: Could not resolve
this reference. Could not locate the assembly "System.IdentityModel". Check to make sure the assembly exists on disk.
If this reference is required by your code, you may get compilation errors. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azu
re.Kusto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.203\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3245: Could not resolve
this reference. Could not locate the assembly "System.IO.Compression". Check to make sure the assembly exists on disk.
If this reference is required by your code, you may get compilation errors. [C:\Code\azure-kusto-nlog-sink\src\NLog.Az
ure.Kusto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.203\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3245: Could not resolve
this reference. Could not locate the assembly "System.Security". Check to make sure the assembly exists on disk. If th
is reference is required by your code, you may get compilation errors. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Ku
sto\NLog.Azure.Kusto.csproj]

2023-05-10 12:30 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXSinkOptions.cs
> +        public string Authority { get; set; }
Can you check the other Apps (Serilog may be) to check if we use Tenant or Authority as the standard

2023-05-10 12:33 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXSinkOptions.cs
> +            kcsb.SetConnectorDetails(AppName, ClientVersion, "Nlog", "5.1.4");
"Nlog", "5.1.4" is probably not a lot of use in the telemetry. What are the things we want to have in telemetry as additional details ?

2023-05-10 12:35 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +            else if (options.ColumnsMapping?.Any() == true)
do we need a == true for a boolean ?

2023-05-10 12:35 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +            KustoConnectionStringBuilder dmkcsb = options.GetKustoConnectionStringBuilder(Constants.CONNECTION_STRING_TYPE.DATA_MANAGEMENT);
Do we set connector details here ?

2023-05-10 12:36 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +                        LeaveOpen = false,
If this option is by default false, then we dont need to set it explicitly

2023-05-10 12:39 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +                    if (ingestionStatus.Status != Status.Pending ||
Question : When logging do we wait for ack of the ingest and status. Think of this , your app where you  include this lib. Everytime we log and flush, the application may expect a pause . May be do this Async ? and do a backout ?

2023-05-10 12:41 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/Constants.cs
> +            public const string ManagedIdentity = "AadManagedIdentity";
ManagedIdentity , not AADManagedIdentity

2023-05-10 12:42 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto.Samples/README.md
> +Install-Package NLog.Azure.Kusto
should we pass version too ?

2023-05-10 12:44 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto.Tests/ADXSInkE2ETest.cs
> +            Assert.NotNull(Environment.GetEnvironmentVariable("DATABASE") ?? throw new ArgumentNullException("DATABASE name not set"));
In the readme, lets have a small section where we mention how to test, in that provide the export commands for these env vars and then do dotnet build ?

2023-05-10 12:46 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXSinkOptions.cs
> +        public AuthenticationMode AuthenticationMode { get; set; }
Should we determine this Automatically ? Say if AppId and AppKey are there then use it , else check ManagedId

2023-05-10 12:47 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto/ADXSinkOptions.cs
> +            switch (this.AuthenticationMode)
KustoConnectionStringBuilder.DefaultPreventAccessToLocalSecretsViaKeywords = false;

needs to be added , this is needed for security purposes

2023-05-10 13:05 UTC, asaharn commented on src/NLog.Azure.Kusto/ADXSinkOptions.cs
> +            kcsb.SetConnectorDetails(AppName, ClientVersion, "Nlog", "5.1.4");
Those are going in place of appName and version, this was taken as reference from Serilog. Alternatively, We can ask users, for setting appName and version as optional?

2023-05-10 13:30 UTC, asaharn commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +            else if (options.ColumnsMapping?.Any() == true)
This code snippet was removed in latest version of code

2023-05-11 05:59 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/ADXLogEvent.cs
> +        public string Level { get; set; }
With the presence of getters and setters, can we change the access specifier of these fields to private.
Also set is nowhere used and since the object instantiation/initialization is happening through constructor, can we remove the setters as well.

2023-05-11 06:45 UTC, tanmaya-panda1 requested changes

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/ADXLogEvent.cs
> +using System.Collections.Generic;
can we remove the unused imports

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +using System.Linq;
unused imports
System.Linq
Kusto.Cloud.Platform.Utils

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +        private int m_ingestionTimeout = 0; //seconds
this initialization seems redundant

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/SinkColumnMapping.cs
> +﻿namespace NLog.Azure.Kusto
Since this class is nowhere used, can we remove this

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/NLog.Azure.Kusto.csproj
> +    <PackageReference Include="Microsoft.Azure.Kusto.Ingest" Version="11.2.2" />
can be upgraded to 11.3.1

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/NLog.Azure.Kusto.csproj
> +    <PackageReference Include="Microsoft.Azure.Kusto.Data" Version="11.2.2" />
can be upgraded to 11.3.1

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/NLog.Azure.Kusto.csproj
> +    <PackageReference Include="Azure.Data.Tables" Version="12.8.0" />
Do we need these Azure.Identity, StorageBlobs, Queues dependencies explicitly? If not can we remove them

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto.sln
> +﻿
can we manage the package version centrally through Directory.Build.Props and Directory.Package.Props

2023-05-11 06:45 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/ADXSinkOptions.cs
> +        private const string ClientVersion = "0.0.1";
shoudlnt this be 1.0.0?

2023-05-11 07:03 UTC, tanmaya-panda1 commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +                var stopWatch = Stopwatch.StartNew();
do we really need ingestionstatus check. Since this sink doesnt promise durability, we just ingest and thats it. If there are any error while ingestion, it can be checked via .show ingestionfailures. Lack of durability should increase the throughput which can be achieved by removing the ingestion status checks. 
@ag-ramachandran what are your thoughts on this?

2023-05-11 12:43 UTC, asaharn commented on src/NLog.Azure.Kusto/ADXTarget.cs
> +            var stream = SRecyclableMemoryStreamManager.GetStream();
I guess this will get disposed  in `Write` method, when it goes out of scope there:

`protected override async void Write(LogEventInfo logEvent)
        {

            using (var datastream = CreateStreamFromLogEvents(ADXLogEvent.GetADXLogEvent(logEvent, RenderLogEvent(Layout, logEvent))))
            {
                var sourceId = Guid.NewGuid();
                IKustoIngestionResult result;

2023-05-15 11:19 UTC, asaharn commented on src/NLog.Azure.Kusto.sln
> +﻿
Done

2023-05-15 11:19 UTC, asaharn commented on src/NLog.Azure.Kusto/NLog.Azure.Kusto.csproj
> +    <PackageReference Include="Azure.Data.Tables" Version="12.8.0" />
Done

2023-05-18 09:12 UTC, ag-ramachandran commented on src/NLog.Azure.Kusto.sln
> +# Visual Studio Version 17
There were couple of null warnings too
`C:\Program Files\dotnet\sdk\7.0.302\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3245: Could not resolve
 this reference. Could not locate the assembly "System.IO.Compression". Check to make sure the assembly exists on disk.
 If this reference is required by your code, you may get compilation errors. [C:\Code\azure-kusto-nlog-sink\src\NLog.Az
ure.Kusto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.302\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3245: Could not resolve
 this reference. Could not locate the assembly "System.Security". Check to make sure the assembly exists on disk. If th
is reference is required by your code, you may get compilation errors. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Ku
sto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.302\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3245: Could not resolve
 this reference. Could not locate the assembly "System.ServiceModel.Web". Check to make sure the assembly exists on dis
k. If this reference is required by your code, you may get compilation errors. [C:\Code\azure-kusto-nlog-sink\src\NLog.
Azure.Kusto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.302\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3243: No way to resolve
 conflict between "System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "Syste
m.IO.Compression". Choosing "System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
arbitrarily. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.302\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3243: No way to resolve
 conflict between "System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Secu
rity". Choosing "System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily. [C:\C
ode\azure-kusto-nlog-sink\src\NLog.Azure.Kusto\NLog.Azure.Kusto.csproj]
C:\Program Files\dotnet\sdk\7.0.302\Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3243: No way to resolve
 conflict between "System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" and "Sys
tem.ServiceModel.Web". Choosing "System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad36
4e35" arbitrarily. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto\NLog.Azure.Kusto.csproj]
  NLog.Azure.Kusto -> C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto\bin\Debug\net6.0\NLog.Azure.Kusto.dll
C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto.Tests\ADXTargetTest.cs(10,40): warning CS0618: 'XmlLoggingConfigurat
ion.XmlLoggingConfiguration(string, bool)' is obsolete: 'Constructor with parameter ignoreErrors has limited effect. In
stead use LogManager.ThrowConfigExceptions. Marked obsolete in NLog 4.7' [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.
Kusto.Tests\NLog.Azure.Kusto.Tests.csproj]
C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto.Tests\ADXSInkE2ETest.cs(138,20): warning CS8603: Possible null refer
ence return. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto.Tests\NLog.Azure.Kusto.Tests.csproj]
C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto.Tests\ADXSInkE2ETest.cs(166,20): warning CS8603: Possible null refer
ence return. [C:\Code\azure-kusto-nlog-sink\src\NLog.Azure.Kusto.Tests\NLog.Azure.Kusto.Tests.csproj]`

2023-05-22 07:39 UTC, ag-ramachandran approved these changes

2023-05-22 08:37 UTC, merged