Replaced IngestionEndpointUri with Kusto ConnectionString
Azure/azure-kusto-nlog-sink pull request #13
Opened 2023-08-08 07:30 UTC by snakefoot

2023-08-14 12:42 UTC, asaharn requested changes
Have added few suggestions and some Test case fixes. 
I have tried pushing changes but couldn't do it. 

 Really thankful for your contribution.

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs
> +            Assert.NotNull(Environment.GetEnvironmentVariable("CONNECTIONSTRING") ?? throw new ArgumentNullException("CONNECTIONSTRING not set"));
```suggestion
            Assert.NotNull(Environment.GetEnvironmentVariable("CONNECTION_STRING") ?? throw new ArgumentNullException("CONNECTION_STRING not set"));
```

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs
>              Assert.NotNull(Environment.GetEnvironmentVariable("APP_KEY") ?? throw new ArgumentNullException("APP_KEY not set"));
Test case needs to be fixed.  SInce it is all done via connection string, app id and other credentials will not be take from env.

Please take reference from https://github.com/Azure/azure-kusto-nlog-sink/blob/feature/ConnectionStringAuth/src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs


```suggestion
            KustoConnectionStringBuilder.DefaultPreventAccessToLocalSecretsViaKeywords = false;
            string dmConnectionStringEndpoint = connectionString.Contains("ingest-") ? connectionString : connectionString.ReplaceFirstOccurrence("://", "://ingest-");
            string engineConnectionStringEndpoint = !connectionString.Contains("ingest-") ? connectionString : connectionString.ReplaceFirstOccurrence("ingest-", "");```

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs
> +            using (var kustoClient = KustoClientFactory.CreateCslAdminProvider(m_kustoConnectionStringBuilder))
```suggestion
           m_kustoConnectionStringBuilder = new KustoConnectionStringBuilder(engineConnectionStringEndpoint);
            m_kustoConnectionStringBuilderDM = new KustoConnectionStringBuilder(dmConnectionStringEndpoint);

            if (m_kustoConnectionStringBuilder == null) throw new Exception("KustoConnectionStringBuilder cannot be created.");
            if (m_kustoConnectionStringBuilderDM == null) throw new Exception("KustoConnectionStringBuilder DM cannot be created.");

            using ICslAdminProvider kustoClient = KustoClientFactory.CreateCslAdminProvider(m_kustoConnectionStringBuilder), kustoClientDM = KustoClientFactory.CreateCslAdminProvider(m_kustoConnectionStringBuilderDM);
```

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs
>                  //Buffer to get commands executed
```suggestion
kustoClientDM.ExecuteControlCommand(database, ".refresh database '" + database + "' table '" + m_generatedTableName + "' cache ingestionbatchingpolicy");
                //Buffer to get commands executed                
```

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs
> +                            ConnectionString = Environment.GetEnvironmentVariable("CONNECTIONSTRING") ?? throw new ArgumentNullException("CONNECTIONSTRING not set"),
```suggestion
                            ConnectionString = Environment.GetEnvironmentVariable("CONNECTION_STRING") ?? throw new ArgumentNullException("CONNECTION_STRING not set"),
```

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Tests/ADXSinkE2ETest.cs
> +                            ConnectionString = Environment.GetEnvironmentVariable("CONNECTIONSTRING") ?? throw new ArgumentNullException("CONNECTIONSTRING not set"),
```suggestion
                            ConnectionString = Environment.GetEnvironmentVariable("CONNECTION_STRING") ?? throw new ArgumentNullException("CONNECTION_STRING not set"),
```

2023-08-14 12:42 UTC, asaharn commented on src/NLog.Azure.Kusto.Samples/NLog.config
> +		ConnectionString="${environment:CONNECTIONSTRING}"
```suggestion
		ConnectionString="${environment:CONNECTION_STRING}"

```

2023-08-16 13:16 UTC, asaharn approved these changes
Some small read me changes.

2023-08-16 18:25 UTC, snakefoot commented on src/NLog.Azure.Kusto.Samples/README.md
Added this to README.md. Guess you can make the final adjustments after merging, when bumping the version-number

2023-08-17 09:34 UTC, ag-ramachandran approved these changes

2023-08-17 09:37 UTC, merged